# Generated by Django 4.2.3 on 2023-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_alter_todo_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
